<?php

use Exts\Configured\ConfigArray;
use Exts\Configured\ConfigLoader;
use Exts\Configured\ConfigStorage;
use Exts\Configured\Loader;
use Exts\Configured\Storage;
use PHPUnit\Framework\TestCase;

/**
 * Class YAMLStorageTest
 */
class ConfigStorageTest extends TestCase
{
    /**
     * @var string
     */
    private $tempFile = '/fixtures/config_storage_saved.yml';

    public function testConfigStorageUsingYAMLStorageInterfaceAndStoredObjectShouldMatchLoadedObject()
    {
        $array = [
            'account' => [
                'user' => [
                    'username' => 'Lamonte',
                    'age' => 25
                ],
                'posts' => 12345
            ]
        ];

        $savePath = __DIR__ . $this->tempFile;

        $arrayObject = new ConfigArray($array);

        $yamlStorage = new Storage\YAML(dirname($savePath));
        $configStorage = new ConfigStorage($yamlStorage);

        $configStorage->store(basename($savePath), (array) $arrayObject);

        $configLoader = new ConfigLoader(new Loader\YAML(dirname($savePath)));
        $data = $configLoader->getArrayObject(basename($savePath));

        $this->assertTrue($data == $arrayObject);
        $this->assertTrue(file_exists($savePath));
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        if(file_exists(__DIR__ . $this->tempFile)) {
            unlink(__DIR__ . $this->tempFile);
        }
    }
}